title       = "csdn"
baseURL     = "https://csdn-cli.tamnd.com/"
description = "A command line for CSDN (CSDN博客), China's largest developer-blog community."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/csdn-cli"
