title       = "csdn"
baseURL     = "https://csdn-cli-cli.tamnd.com/"
description = "Browse CSDN Chinese developer articles"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/csdn-cli-cli"
